on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  CONTAINER_NAME: trevari-web
  SEPARATOR_PATH: kubernetes-resources/overlays/prod/front

permissions:
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Register whitelist ip
        run: |
          curl --request POST --url "http://local-config.trevari.co.kr/ips" --header 'X-PROXY-TOKEN:${{ secrets.X_PROXY_TOKEN }}'

      - name: Download env from config server
        run: |
          rm -f .env
          curl -X GET "http://local-config.trevari.co.kr/application-node.yml" > .env
          sed -i -e 's/: /\=/g' .env
          rm -f .env-e

      - name: make .npmrc
        run: |
          echo -e //npm.pkg.github.com/:_authToken=${{ secrets.GIT_PASSWORD }} >> .npmrc
          cat .npmrc

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present

      - name: Login to Trevari Container Registry
        uses: docker/login-action@v1
        id: login-tcr
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Build, tag, and push image to Trevari docker registry
        id: build-image
        env:
          IMAGE_TAG: ${{steps.current-time.outputs.formattedTime}}
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/$CONTAINER_NAME:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_REGISTRY }}/$CONTAINER_NAME:$IMAGE_TAG
          docker image tag ${{ secrets.DOCKER_REGISTRY }}/$CONTAINER_NAME:$IMAGE_TAG ${{ secrets.DOCKER_REGISTRY }}/$CONTAINER_NAME:latest
          docker push ${{ secrets.DOCKER_REGISTRY }}/$CONTAINER_NAME:latest
          echo "::set-output name=image::${{ secrets.DOCKER_REGISTRY }}/$CONTAINER_NAME:$IMAGE_TAG"

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout kustomize repository
        uses: actions/checkout@v3
        with:
          repository: trevari/kubernetes-resources
          ref: main
          token: ${{ secrets.ACTION_TOKEN }}
          path: kubernetes-resources

      - name: Update Kubernetes resources
        run: |
          echo \${{ secrets.DOCKER_REGISTRY }}/$CONTAINER_NAME=\${{ steps.build-image.outputs.image }}
          cd kubernetes-resources/overlays/prod/front
          kustomize edit set image \${{ secrets.DOCKER_REGISTRY }}/$CONTAINER_NAME=\${{ steps.build-image.outputs.image }}
          cat kustomization.yaml

      - name: Commit files
        run: |
          cd kubernetes-resources
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Update image tag"
          git push -u origin main
